server:
  port: 8082

spring:
  application:
    name: request-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/campusflow_requests}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

gcp:
  project-id: ${GCP_PROJECT_ID:GCP_PROJECT_ID_HERE}
  storage:
    bucket-name: ${GCS_BUCKET_NAME:campusflow-attachments}

jwt:
  secret: ${JWT_SECRET:campusflow-local-dev-secret-key-that-is-at-least-256-bits-long}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
